### ISSUE TITLE
No sources

### ISSUE THREAD

**Issue by wahidr97** [XenTeckzX/FireAnime#11]
The new 2.0 version has no sources and then the app crashes

**Comment by deshant** [comment]
For gogoanime server it says no streams available.
For 9anime the app is stuck on splash screen.

**Comment by XenTeckzX** [comment]
Fixed Please download update 2.1
The issue was the domain name changes

**Comment by XenTeckzX** [comment]
What anime are you trying to watch i've just tested and everything seems okay. The only problem i can think off is that if you saved anime on the watch list they might be outdated and may need to be removed then re-added using the search bar again since gogoanime changed its url name

**Comment by Randomdude707** [comment]
Hey man thanks I was having the same issue but you were right just clear your watchlist and force close the app then it works ( keep up the amazing work on the app this is really unique and as far as I can tell this is really the first anime app ever on the fire stick that works so thank you )
