### ISSUE TITLE
grey pillarboxing on 480p

### ISSUE THREAD

**Issue by fggxf** [XenTeckzX/FireAnime#13]
Version 2.2
As the tittle states, the pillarboxing mattes are grey instead of black on 480p content while using the internal player.

They are the correct color when using an external player.

**Comment by XenTeckzX** [comment]
Unfortunately i'm using googles library for the internal player which provides limited capability for making changes to the pillar boxes. But with the ability of external players you can just choose the player of your choice.

Thanks the feedback 👍

**Comment by fggxf** [comment]
Thanks for the reply. Mxplayer performs much better than the internal player anyways so I'll just use that.
