### ISSUE TITLE
host request

### ISSUE THREAD

**Issue by csong95** [XenTeckzX/FireAnime#15]
could you add animeultima.eu super fast/ up to date and has both sub & dubs

**Comment by XenTeckzX** [comment]
it has clouldflare check so i can't add this as a source at the moment until i find a way to bypass it

**Comment by pervertkirito** [comment]
> 
> 
> it has clouldflare check so i can't add this as a source at the moment until i find a way to bypass it

Hey, I know this issue is closed but maybe you can copy from this app called [Tachiyomi](https://github.com/inorichi/tachiyomi) about how to bypass cloudflare?
