### ISSUE TITLE
Fix your app (fireanime ) 

### ISSUE THREAD

**Issue by kingkiddarkness** [XenTeckzX/FireAnime#17]
The app was good and now it’s taking a fall I and others can’t watch our shows we like because they either aren’t showing or the link don’t work and the app acts up plz come out with a better update to fix these problems we like your app and glad for it but we need to work thank for your work and time given we just wanna see this app grow

**Comment by Randomdude707** [comment]
I thought I would just give you a suggestion to use while Fireanime is down use anyme  (https://anyme.app/apk) to watch anime and if you wanna watch it on your TV just use this casting app with it (https://drive.google.com/file/d/1ugfxvhmX8k7-DwSD7Mh8Mk30muJWkon4/view?usp=drivesdk) hope this helps. 

Just remember that the developer is just one person and they can't meet the demands of everyone it takes time I'm not trying to be rude I'm just being honest.

**Comment by XenTeckzX** [comment]
whats wrong with the app need more details...

**Comment by kingkiddarkness** [comment]
Like certain shows don’t play and some anime’s show are hard to find due to
the  navigation from up for example I was the rising shield hero and now I
can’t find it so I’m currently not using the app because it won’t work
correctly . I own two fire sticks but on them they their acting correctly.

Thanks for reaching back to me.

**Comment by XenTeckzX** [comment]
which server were you using eg Gogoanime, 9anime ect?

**Comment by XenTeckzX** [comment]
i've tested this issue on 3 different servers gogoanime, watchcartoonsonline and OtakuStream

https://prnt.sc/nuiy7u 

and they all work fine

**Comment by kingkiddarkness** [comment]
Okay I’ll check it out thanks ☺️
