### ISSUE TITLE
Stream issues 

### ISSUE THREAD

**Issue by drowsybike** [XenTeckzX/FireAnime#18]
Some anime on gogo the stream list won’t load

**Comment by XenTeckzX** [comment]
what anime and what episode

**Comment by drowsybike** [comment]
Slime data ken the whole list won’t load 
![image](https://user-images.githubusercontent.com/54242651/63226556-fc32ee80-c1d2-11e9-91a3-3ea6c7f65344.jpg)

**Comment by drowsybike** [comment]
And I tried to uninstall and reinstall but it still didn’t work

**Comment by XenTeckzX** [comment]
its an issue with the app will fix this and release a hot fix soon,
if you choose another add-on on Fire anime you can still watch it.
For Dubbed i recommend using watchcartoonsonline 
For Subbed i recommend otakustream or Anime Twist

**Comment by XenTeckzX** [comment]
Thanks for the feedback :)

**Comment by drowsybike** [comment]
Thank you I thought it was something wrong with the when will you be able to fix it a  estimated time if possible

**Comment by drowsybike** [comment]
MP4 for Hunter x Hunter didn’t work for me either

**Comment by drowsybike** [comment]
It was random eps but ep 12 was one

**Comment by XenTeckzX** [comment]
i'd say 1 -2 days before i either release a hotfix or a beta version for people to test

**Comment by drowsybike** [comment]
Ok

**Comment by XenTeckzX** [comment]
in the meantime you can use one of the other add-ons on Fire Anime they work just as well

**Comment by drowsybike** [comment]
Ok thank you
