### ISSUE TITLE
No anime is  loading on any  source 

### ISSUE THREAD

**Issue by drowsybike** [XenTeckzX/FireAnime#19]
Please help

**Comment by drowsybike** [comment]
I can’t view any anime at all

**Comment by XenTeckzX** [comment]
which add on are you using gogoanime watchcartoonsonline ect

**Comment by drowsybike** [comment]
All of them

**Comment by drowsybike** [comment]
Default player

**Comment by drowsybike** [comment]
I can’t see the latest anime list at all

**Comment by XenTeckzX** [comment]
just tested it on my android phone and amazon fire tv and it works fine

**Comment by XenTeckzX** [comment]
what device are you using?

**Comment by drowsybike** [comment]
Nvm it fixed itself after my fire stick updated thank you though
