### ISSUE TITLE
Can't download FireAnime

### ISSUE THREAD

**Issue by chrissyt29** [XenTeckzX/FireAnime#2]
Trying to download FireAnime on my android box but it just gives me an error page when I click the download link

**Comment by Randomdude707** [comment]
Try this https://github.com/XenTeckzX/FireAnime/raw/master/FireAnimeTemporaryFix.apk

**Comment by chrissyt29** [comment]
Got that and it says it installed but wouldn't let me open it and can't find it in my apps

**Comment by Randomdude707** [comment]
Well I guess since your using a tv box it didn't work since this app is meant for the firestick sorry my dude
