### ISSUE TITLE
2 features/improvements

### ISSUE THREAD

**Issue by Brianmm94** [XenTeckzX/FireAnime#20]
Hello, I've been using your app for a very long time (like a year now), and there are two critical features I feel are missing from the app.

1. When clicking left/right on my fire tv stick, it would be nice to go up/down in a multiple of 20 episodes. As of right now, you can sort it ascending/descending or move up/down 1 episode by pushing up or down, but you need something to navigate through the episodes quicker.

2. You should have which video player you use as a one time configurable thing rather than needing to select your video player every time you choose your video (I shouldn't need to select mx player every single time I want to watch an episode). I don't see anybody wanting to use a different video player for each episode they watch. If you don't want this as a one time configurable thing, I suggest making it so that users can somehow change which order the video players appear in (such as mx player first in the list).

**Comment by XenTeckzX** [comment]
1. Great idea, i'll add it to the next update
2. It's already been added in the settings menu, its called Set player which bypasses the whole select a player screen entirely

**Comment by Brianmm94** [comment]
1. Okay, great!
2. Oh, I didn't even know that was added, haha.
