### ISSUE TITLE
animeultima app/server issues

### ISSUE THREAD

**Issue by Delacambriole03** [XenTeckzX/FireAnime#24]
animeultima is not working properly as when I try to stream episode of certain anime such as black clover, one piece, naruto, bleach and else, It will stream an unrelated anime. can it be fixed?

**Comment by XenTeckzX** [comment]
yep currently working on it will release a hotfix in about 24hours from now

**Comment by XenTeckzX** [comment]
also would have messaged you on Reddit but my accounts been caught in a spam filter so I'm currently waiting for Reddit to fix it :(

**Comment by Delacambriole03** [comment]
thank you

**Comment by Delacambriole03** [comment]
I checked yesterday.  it is still not fixed

**Comment by XenTeckzX** [comment]
apparently there's an issue with watch cartoons online trying to fix it before I release a new update but when testing it on my machine watch cartoons online works fine

**Comment by XenTeckzX** [comment]
Should be fixed now, try downloading the latest update 3.1.5

**Comment by Delacambriole03** [comment]
thank you
