### ISSUE TITLE
No stream available watch cartoons online 

### ISSUE THREAD

**Issue by big1sofun** [XenTeckzX/FireAnime#25]
Some users saying no stream available on watch cartoons online on version 3.1 just passing on the word since your reddit account shadow banned. I don’t understand I’m on 3.1 and watch cartoons online gives me links so problem on any anime I try

**Comment by XenTeckzX** [comment]
Should be fixed now, try downloading the latest update 3.1.5, also thanks Reddit user https://www.reddit.com/user/Charaznable89/ for some very helpful feedback made fixing the bug a lot easier :)
