### ISSUE TITLE
[Enhancement] Addon for the Kodi Community

### ISSUE THREAD

**Issue by Goldenfreddy0703** [XenTeckzX/FireAnime#29]
This is not an issue but an enhancement, I love this apk and what it provides and i love your project so much that i want this to be an addon for kodi users for the community, I love everything about your apk and what it took to make this, it shows all the fanart and metadata from other anime sites that are really interesting especially Gogo Anime. The only enhancements that i would like you to add if possible is Accounts to keep track of your anime that can go with your watch list sections for your apk. Some accounts people use to track there anime is Kitsu, MAL, and AniList. One last enhancement i would like you to add is a kodi addon for your apk if that's possible with metadata and fanart from Kitsu, MAL, or AniList. If you could make these two Enhancements than you will be the number one person kodi users will look upto for anime.

**Comment by XenTeckzX** [comment]
Kodi addons are written in python, unfortunately, I don't know any python therefore I cant fulfill your request. That and one person managing 2 separate applications in 2 different languages would be impossible to maintain

**Comment by Goldenfreddy0703** [comment]
Awww ok man but thank you for your help and I appreciate your application so much.
