### ISSUE TITLE
Pause Button on Non Amazon Devices

### ISSUE THREAD

**Issue by Fakenews1729** [XenTeckzX/FireAnime#3]
First i want to thank you for putting together an anime app with leanback support. '

I am using this apk on the Mi Box. At the moment i am unable to pause the video once it plays. 

I have tried to pause through the video player and that wont work either. 

Is there a way to hotkey the okay/middle button to recognize as pause for the non amazon users?

Thanks again for all the hard work!

**Comment by XenTeckzX** [comment]
does the rewind and fast forward hotkeys work? or is it only for the pause button?

**Comment by XenTeckzX** [comment]
i think i might have fixed it but since i don't own a mi box i cant test it. I've updated the app to 1.4 if you can download the new version and test the pause button for me that would be great.

**Comment by XenTeckzX** [comment]
if you update the app over the existing app your watch list should stay. The only time your watch list goes is when you uninstall the application. i will look into this more and message you back if i find a fix

**Comment by Fakenews1729** [comment]
I have downloaded the version 1.4. The rewind and forward hotkeys works very smoothly, unfortunately the pause button still doesn't work.  i think adding a long pressing the selection button as a substitute for pausing might work.

**Comment by ruegnueg** [comment]
actually bout 90% I use LibreELEC on my nuc with the 9anime addon. but I like fireanime on my firetv. but as you mentioned it's designed for Android TV. so a version for regular Android would be cool for phones and Tabs 😁 but it's just an idea. you did great. maybe Integration of the 9anime Account and watchlist would be awesome though. :-)

**Comment by XenTeckzX** [comment]
Fixed pause button download latest update
