### ISSUE TITLE
Having trouble loading GoGoAnime - India

### ISSUE THREAD

**Issue by earendildev** [XenTeckzX/FireAnime#35]
In India the url _gogoanime.so_, has been blocked completely for all ISP's.

Gogoanime has switched to a new url _https://gogoanime.sh/_ which works for now...

Is it possible to implement this change in the app?

**Comment by earendildev** [comment]
Done 👍🏼 
Thank You for this amazing App 🙏🏼

**Comment by UdaySriHarsha** [comment]
Now .pe
