### ISSUE TITLE
Gogoanime not working

### ISSUE THREAD

**Issue by JeiPii11** [XenTeckzX/FireAnime#37]
In gogoanime when i click an episode nothing happens..

**Comment by cureamethyst** [comment]
Im experiencing the same issue my app was working fine last night now it isnt

**Comment by UdaySriHarsha** [comment]
Same issue, but main website is functional, might be webclient issue which it's not able to fetch/parse gogolinks

**Comment by UdaySriHarsha** [comment]
For now AnimePahe is alternative for GoGoAnime @JeiPii11 
@cureamethyst

**Comment by UdaySriHarsha** [comment]
> For now AnimePahe is alternative for GoGoAnime @JeiPii11
> @cureamethyst

MX and inbuilt players can access Kwik server if directly set

**Comment by JeiPii11** [comment]
Guys, It works fine now after i update

Thanks Devs
