### ISSUE TITLE
No sources

### ISSUE THREAD

**Issue by Osoreru9281** [XenTeckzX/FireAnime#4]
Started a bit ago but every time i click to watch a episode of any anime just sends me to a quick grey screen and then back to the episode list

**Comment by XenTeckzX** [comment]
What anime were you trying to watch?

**Comment by Osoreru9281** [comment]
tried it on Boruto, Rec, and White album but it looks like its working again now and i havent had the problem since updating to the newest file

**Comment by Osoreru9281** [comment]
Also i noticed White album and White album 2 have the same content looks like both of them are White album and no signs of White album 2 if that makes sense

**Comment by XenTeckzX** [comment]
i will be adding more sources in the future for now there's nothing i can do.
