### ISSUE TITLE
Continuous fast-forward or rewind not working

### ISSUE THREAD

**Issue by praveencbe0in** [XenTeckzX/FireAnime#7]
Huge fan of this apk.

Continuous fast-forward or rewind not working

When I press the right button, it skips 10 seconds, then the popup for the Navigation shows up and then if I press right button again it does not work.

Figured it when Navigation pane shows up the right and left D-pad gets disabled.
Right D-pad = fast-forward by 10 secs
Left D-pad = rewind by 10 secs

If I hide the Navigation pane/bar using the back button, then again the right and left works for one time and navigation bar shows up again.

My recommendation when clicking left or right I don't want to the Navigation bar to show up Just skipping seconds would be fine.

Testing it on NVIDIA SHIELD.

**Comment by XenTeckzX** [comment]
Usually for the fire stick if you press the fast forward button it will continuously fast forward but since the  nvidia shield doesn't have the buttons on the remote you don't really have that option.

This should be fixed in the next update.

**Comment by XenTeckzX** [comment]
This issue is now obsolete due to the ability to select external players which handle playing a videos a lot better.

Thanks for the feedback 👍
